server:
  port: 8888


## 数据源配置
db:
  druid:
    url: jdbc:mysql://localhost/task?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 3
    minIdle: 3
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select '1+1'
    testWhileIdle: true

## JSP
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
## JPA
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

## RabbitMQ
  rabbitmq:
    host: 192.168.234.250
    publisher-confirms: true
    port: 5672
    username: root
    password: root
    virtual-host: /spider

## 自定义属性
local:
  path: D:/meizitu/





