server:
  port: 8888


## 数据源配置
db:
  druid:
    url: jdbc:mysql://localhost/task?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 3
    minIdle: 3
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select '1+1'
    testWhileIdle: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hacker.entity
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
local:
  path: D:/meizitu/

